baseURL = '/'
languageCode = 'en-us'
title = 'TWApps'
paginate = 5
disableKinds = ["taxonomy"]

[params]
name = "Tobias Werner"

[markup.goldmark.renderer]
unsafe= true

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true