baseURL = 'https://wwww.twapps.net/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
name = "Tobias Werner"

[markup.goldmark.renderer]
unsafe= true

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true