name: Build & Deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Upload Page Artifact
        uses: actions/upload-artifact@v3
        with:
          name: twappsnet
          path: public/
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Page Artifact
      uses: actions/download-artifact@v3
      with:
        name: twappsnet
    - name: Deploy
      run: rsync -avz public/ ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_PASS }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
